# This is a basic workflow to help you get started with Actions

name: try-gatling

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0

      # Checks-out under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apache2-utils

      - name: Start short run
        run: |
          npm run start

      - name: Start long run
        run: |
          npm run start-long
